SPACESHIP_TOOLBOX_SHOW="${SPACESHIP_TOOLBOX_SHOW=true}"
SPACESHIP_TOOLBOX_PREFIX="${SPACESHIP_TOOLBOX_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"}"
SPACESHIP_TOOLBOX_SUFFIX="${SPACESHIP_TOOLBOX_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"}"
SPACESHIP_TOOLBOX_SYMBOL="${SPACESHIP_TOOLBOX_SYMBOL="⬢ "}"
SPACESHIP_TOOLBOX_COLOR="${SPACESHIP_TOOLBOX_COLOR="cyan"}"

spaceship_toolbox(){
  [[ $SPACESHIP_TOOLBOX_SHOW == false ]] && return

  [[ -f /run/.containerenv  &&  -f /run/.toolboxenv ]] || return

  spaceship::section \
    "${SPACESHIP_TOOLBOX_COLOR}" \
    "${SPACESHIP_TOOLBOX_PREFIX}" \
    "${SPACESHIP_TOOLBOX_SYMBOL}toolbox" \
    "${SPACESHIP_TOOLBOX_SUFFIX}"
}
